config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get 'users', to:'users/registrations#new'
  end
  resources :users, only: [:show]
  resources :diaries, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :schedules, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :exercises, only:[:new, :create, :show, :index, :edit, :update, :destroy]
  resources :counts, only: [:create, :update, :show]
  root 'exercises#index'
end

app/models/diary.rb
class Diary < ApplicationRecord

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  mount_uploader :image, ImageUploader

  validates :content, presence: true, length: { maximum: 200 }
  validates :image, presence: { message: 'が添付されていません' }

  private

end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @diaries = Diary.all.order(id: "DESC")
  end

  def show
    @diary = Diary.find(params[:id])
    if like = Like.find_by(user_id: current_user.id, diary_id: params[:id])
      @like = like
    else
      @like = Like.new
    end
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      flash[:notice] = '投稿が完了しました'
      redirect_to diaries_path
    else
      flash.now[:alert] = '入力を確認してください'
      render :new
    end
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      flash[:notice] = '編集が完了しました'
      redirect_to diary_path(@diary)
    else
      flash.now[:alert] = '入力を確認してください'
      render :edit
    end
  end

  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
    flash[:notice] = '１件の日記を削除しました'
    redirect_to diaries_path
  end

  private

  def diary_params
    params.require(:diary).permit(:content, :image).merge(user_id: current_user.id)
  end

  def correct_user
    diary = Diary.find(params[:id])
    redirect_to root_url unless current_user.id == diary.user_id
  end

end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_likes.html.erb
<div class="diary_like">
  <% if current_user.already_liked?(@diary) %>
    <%= link_to diary_like_path(@diary, @like), method: :delete, class: "like-button", remote: true do %>
      <i class="fa fa-heart heart_red" aria-hidden="true"></i>
      <span><%= @diary.likes.count %></span>
    <% end %>
  <% else %>
    <%= link_to diary_likes_path(@diary), method: :post, class: "like-button", remote: true do %>
      <i class="fa fa-heart heart_gray" aria-hidden="true"></i>
      <span><%= @diary.likes.count %></span>
    <% end %>
  <% end %>
</div>
<div class="diary-like-users">
  <% @diary.liked_users.each do |user| %>
    <div class="diary-like-user">
      <%= link_to user_path(user), class: "link" do %>
        <% if @diary.user.image? %>
          <%= image_tag @diary.user.image_url(:thumb20), class: "user_icon_tag" %>
        <% else %>
          <%= image_tag 'user_image.png', :size =>'20x20', class: "user_icon_tag" %>
        <% end %>
      <% end %>
      <%= user.name %>
    </div>
  <% end %>
</div>

app/views/diaries/edit.html.erb
<%= javascript_include_tag 'diary/edit.js' %>
<%= javascript_include_tag 'diary/height.js' %>
<%= javascript_include_tag 'style/diary_preview.js' %>

<%= form_with model: @diary, local: true, method: :patch do |f| %>
  <div class="user-content show-diary edit-diary">
    <div class="show_wrapper">
      <div class="content_show">
          <div class="content">
            <div class="diary-title">
              <div class="diary_user">
                <div class="user_icon">
                  <% if @diary.user.image? %>
                    <%= image_tag @diary.user.image_url(:thumb30), class: "user_icon_tag" %>
                  <% else %>
                    <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                  <% end %>
                  <span class="user_name">
                    <%= "1件の日記を編集中" %>
                  </span>
                </div>
              </div>
              <% if user_signed_in? && current_user.id == @diary.user_id %>
                <div class="diary-edit-menu">
                  <i class="fas fa-ellipsis-h color"></i>
                </div>
                <div class="edit-menu">
                  <li><%= link_to "削除", diary_path(@diary), method: :delete, class: "link" %></li>
                </div>
              <% end %>
            </div>

            <div class="prev-contents">
              <div class="prev-content">
                <%= image_tag "#{@diary.image}", class: "diary_image prev-image", onClick: "$('#upfile').click()" %>
              </div>
            </div>

            <div class="">
              <%= f.label :image, {class: "content-label hidden_file"} %>
              <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', id: 'upfile', class:"hidden_file" %>
            </div>
            <div class="">
              <%= f.label :content, "今日の日記", {class: "content-label"}  %>
              <%= f.text_area :content, class: "form-control" %>
            </div>
            <%= render 'layouts/error_messages', model: @diary %>
            <div class="diary_info">
              <div class="diary-submit">
                <%= f.submit "更新", class: "btn btn-primary" %>
              </div>
              <div class="diary_day">
                <%= l @diary.created_at %>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/diaries/index.html.erb
<div class="user-content index-diary">
  <div class="show_wrapper">
    <div class="title_style">
      <h2 class="title"><i class="fas fa-angle-right space"></i>みんなの日記</h2>
        <%= link_to new_diary_path, class: "link" do %>
          <i class="fa fa-edit" aria-hidden="true"></i>
          <span class="pc_character">日記を投稿</span>
          <span class="smart_character">投稿</span>
        <% end %>
    </div>
    <div class="content_show">
      <% @diaries.each do |diary| %>
        <div class="content">
          <%= link_to user_path(diary.user.id), class: "link" do %>
            <div class="diary_user">
              <div class="user_icon">
                <% if diary.user.image? %>
                  <%= image_tag diary.user.image_url(:thumb30), class: "user_icon_tag" %>
                <% else %>
                  <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                <% end %>
              </div>
              <div class="user_name">
                <%= diary.user.name %>
              </div>
            </div>
          <% end %>
          <%= link_to diary_path(diary), class: "link" do %>
            <img src="<%= diary.image %>" class="diary_image" alt="日記画像">
            <li class="diary_content"><%= diary.content %></li>
          <% end %>
          <div class="diary_info">
            <div class="diary_like">
              <i class="fa fa-heart heart_red" aria-hidden="true"></i>
              <%= diary.likes.count %>
            </div>
            <div class="diary_day">
              <%= l diary.created_at %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/new.html.erb
<%= javascript_include_tag 'diary/height.js' %>
<%= javascript_include_tag 'style/diary_preview.js' %>

<%= form_with model: @diary, local: true, method: :post do |f| %>
  <div class="user-content show-diary edit-diary">
    <div class="show_wrapper">
      <div class="content_show">
        <div class="content">
          <div class="diary-title">
            <div class="diary_user">
              <div class="user_icon">
                <% if current_user.image? %>
                  <%= image_tag current_user.image_url(:thumb30), class: "user_icon_tag" %>
                <% else %>
                  <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                <% end %>
                <span class="user_name">
                  <%= "新しい日記を作成中" %>
                </span>
              </div>
            </div>
          </div>
          <%= render 'layouts/error_messages', model: f.object %>

          <div class="prev-contents">
            <div class="prev-content">
              <%= image_tag 'diary_image.png', class: "diary_image prev-image", onClick: "$('#upfile').click()" %>
            </div>
          </div>

          <div class="">
            <%= f.label :image, {class: "content-label hidden_file"} %>
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', id:'upfile', class:'hidden_file' %>
          </div>
          <div class="">
            <%= f.label :content, "今日の日記", {class: "content-label"}  %>
            <%= f.text_area :content, class: "form-control" %>
          </div>
          <div class="diary_info">
            <div class="diary-submit">
              <%= f.submit "投稿する", class: "btn btn-warning color" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/diaries/show.html.erb
<%= javascript_include_tag 'diary/edit.js' %>
<div class="user-content show-diary">
  <div class="show_wrapper">
    <div class="content_show">
        <div class="content">

          <div class="diary-title">
            <%= link_to user_path(@diary.user.id), class: "link" do %>
              <div class="diary_user">
                <div class="user_icon">
                  <% if @diary.user.image? %>
                    <%= image_tag @diary.user.image_url(:thumb30), class: "user_icon_tag" %>
                  <% else %>
                    <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                  <% end %>
                  <span class="user_name">
                    <%= @diary.user.name %>
                  </span>
                </div>
              </div>
            <% end %>
            <% if user_signed_in? && current_user.id == @diary.user_id %>
              <div class="diary-edit-menu">
                <i class="fas fa-ellipsis-h color"></i>
              </div>
              <div class="edit-menu">
                <li><%= link_to "編集", edit_diary_path, class: "link" %></li>
                <li><%= link_to "削除", diary_path(@diary), method: :delete, class: "link" %></li>
              </div>
            <% end %>
          </div>
          <%= link_to diary_path(@diary), class: "link" do %>
            <img src="<%= @diary.image %>" class="diary_image" alt="日記画像">
            <li class="diary_content"><%= @diary.content %></li>
          <% end %>
          <div class="diary_info">
            <div class="like-user">
                <%= render partial:'diaries/likes'%>
            </div>
            <div class="diary_day">
              <%= l @diary.created_at %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>