config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get 'users', to:'users/registrations#new'
  end
  resources :users, only: [:show]
  resources :diaries, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :schedules, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :exercises, only:[:new, :create, :show, :index, :edit, :update, :destroy]
  resources :counts, only: [:create, :update, :show]
  root 'exercises#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  validates :name, presence: true, uniqueness: true, length: { maximum: 15 }
  VALID_PASSWORD_REGEX =/\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,12}\z/
    validates :password,
              format: { with: VALID_PASSWORD_REGEX,
              message: "パスワードは半角6~12文字英大文字・小文字・数字それぞれ１文字以上含む必要があります"}
  validates_presence_of :password, if: :password_required?
  mount_uploader :image, ImageUploader
  has_many :diaries, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :exercise, dependent: :destroy
  has_one :count, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_diaries, through: :likes, source: :diary

  def already_liked?(diary)
    self.likes.exists?(diary_id: diary.id)
  end

  def self.guest
    find_or_create_by(email: "test@example.com") do |user|
      user.password = 'Testtest1'
      user.name = 'テストユーザー'
    end
  end

  # def update_without_password(params, *options)
  #   params.delete(:current_password)
  #   params.delete(:password)
  #   params.delete(:password_confirmation)
  #   @params = params
  #   result = update_attributes(params, *options)
  #   clean_up_passwords
  #   result
  # end

  def update_without_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
        params.delete(:password)
        params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    @params = params
    result = update(params, *options)
    clean_up_passwords
    result
  end

  def password_required?
    if @params.nil? || @params.has_key?(:current_password_password) ||@params.has_key?(:password_confirmation) || @params.has_key?(:password)
      true
    else
      false
    end
  end

  # def password_required?
  #   false
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def update_resource(resource, params)
  #   resource.update_without_current_password(params)
  # end

  def update_resource(resource, params)
    if params[:password].present? && params[:password_confirmation].present?
      resource.update_with_password(params)
    else
      resource.update_without_password(params)
    end
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "テストユーザーとしてログインしました"
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @diaries = Diary.where(user_id: @user.id)
    @schedules = Schedule.where(user_id: @user.id).order(training_date: :asc)
    @exercises = Exercise.where(user_id: @user.id)
    @likes_count = Like.where(user_id: @user.id).count
    @count = Count.find_by(user_id: @user.id)

    if @count.nil?
      @count = Count.create(day: 0, user_id: @user.id)
    end

    # レベルアップの条件式
    if @count.day >= 15
      @level = 6
      @level_up_day = 0
    elsif @count.day >= 10
      @level = 5
      @level_up_day = 15 - @count.day
    elsif @count.day >= 6
      @level = 4
      @level_up_day = 10 - @count.day
    elsif @count.day >= 3
      @level = 3
      @level_up_day = 6 - @count.day
    elsif @count.day >= 1
      @level = 2
      @level_up_day = 3 - @count.day
    else
      @level = 1
      @level_up_day = 1 - @count.day
    end
    @character = Character.find(@level)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= javascript_include_tag 'users/show.js' %>
<div class="user_wrapper">
  <div class="user_show">
    <div class="user_style">
      <div class="user_image">
        <% if @user.image? %>
          <%= image_tag @user.image_url(:thumb50), class: "icon-image" %>
        <% else %>
          <%= image_tag 'user_image.png', :size =>'50x50', class: "icon-image" %>
        <% end %>
      </div>
      <div class="user_info">
        <div class="user_name">
          <%= @user.name %>
        </div>
        <div class="user_character">
          <p><%= "ユーザーレベル#{@level}" %></p>
          <%= image_tag @character.image, :size =>'200x200', class: "character_image_tag" %>
          <p><%= "今日は#{@count.day}日目"%></p>
          <p><%= "あと#{@level_up_day}日でレベルUP！" %></p>
        </div>
        <div class="user_edit">
          <% if user_signed_in? && current_user.id == @user.id %>
            <%= link_to edit_user_registration_path, class: "link" do %>
              <i class="fa fa-edit edit_icon"></i>
              <%= "編集" %>
            <% end %>
            <%= link_to user_registration_path, method: :delete, class: "link",
                                data: { confirm: "【確認】アカウントを削除してもよろしいですか？" } do %>
              <i class="fa fa-trash"></i>
              <%= "退会" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="user-content">
    <%# 自分の日記 %>
    <div class="show_wrapper">
      <div class="title_style">
        <h2 class="title"><i class="fas fa-angle-right space"></i>自分の日記</h2>
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to new_diary_path, class: "link" do %>
            <i class="fa fa-edit" aria-hidden="true"></i>
            <span class="pc_character">日記を投稿</span>
            <span class="smart_character">投稿</span>
          <% end %>
        <% end %>
      </div>
      <div class="content_hidden">
        <div class="content_show">
          <% if @diaries.empty? %>
            <p>まだ投稿された日記はありません</p>
          <% else %>
            <% @diaries.each do |diary| %>
              <div class="content">
                <%= link_to user_path(diary.user.id), class: "link" do %>
                  <div class="diary_user">
                    <div class="user_icon">
                      <% if diary.user.image? %>
                        <%= image_tag diary.user.image_url(:thumb30), class: "user_icon_tag" %>
                      <% else %>
                        <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                      <% end %>
                    </div>
                    <div class="user_name">
                      <%= diary.user.name %>
                    </div>
                  </div>
                <% end %>
                <%= link_to diary_path(diary), class: "link" do %>
                  <img src="<%= diary.image %>" class="diary_image" alt="日記画像">
                  <li class="diary_content"><%= diary.content %></li>
                <% end %>
                <div class="diary_info">
                  <div class="diary_like">
                    <i class="fa fa-heart heart_red" aria-hidden="true"></i>
                    <%= diary.likes.count %>
                  </div>
                  <div class="diary_day">
                    <%= l diary.created_at %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <%# いいねした日記 %>
    <div class="show_wrapper other_show">
      <div class="title_style">
        <h2 class="title"><i class="fas fa-angle-right space"></i>いいねした投稿</h2>
      </div>
      <div class="content_hidden">
        <div class="content_show">
          <% if @user.liked_diaries.blank? %>
            <p>まだいいねした日記はありません</p>
          <% else %>
            <% @user.liked_diaries.each do |diary| %>
              <div class="content">
                <%= link_to user_path(diary.user.id), class: "link" do %>
                  <li class="diary_user">
                    <% if diary.user.image? %>
                      <%= image_tag diary.user.image_url(:thumb30), class: "user_icon_tag" %>
                    <% else %>
                      <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                    <% end %>
                    <span class="user_name"><%= diary.user.name %></span>
                  </li>
                <% end %>
                <%= link_to diary_path(diary), class: "link" do %>
                  <img src="<%= diary.image %>" class="diary_image" alt="日記画像">
                  <li class="diary_content"><%= diary.content %></li>
                <% end %>
                <div class="diary_info">
                  <div class="diary_like">
                    <i class="fa fa-heart heart_red" aria-hidden="true"></i>
                    <%= diary.likes.count %>
                  </div>
                  <div class="diary_day">
                    <%= l diary.created_at %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <%# エクササイズ管理 %>
    <div class="show_wrapper other_show">
      <div class="title_style">
        <h2 class="title"><i class="fas fa-angle-right space"></i>エクササイズ</h2>
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to new_exercise_path, class: "link" do %>
            <i class="fa fa-edit" aria-hidden="true"></i>
            <span class="pc_character">エクササイズを追加</span>
            <span class="smart_character">追加</span>
          <% end %>
        <% end %>
      </div>
      <div class="content_hidden">
        <div class="content_show">
          <% if @exercises.empty? %>
            <p>まだ登録されたエクササイズはありません</p>
          <% else %>
            <% @exercises.each do |exercise| %>
              <div class="content exercise_content">
                <div class="exercise_info">
                  <span class="level">
                    <% exercise.level.times do %>
                      <i class="fas fa-dumbbell"></i>
                    <% end %>
                  </span>
                  <%= exercise.part %>
                </div>
                <div class="iframe_wrap">
                  <iframe width="400" height="225" src="https://www.youtube.com/embed/<%= exercise.url.last(11) %>"
                          frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                          gyroscope; picture-in-picture" allowfullscreen>
                  </iframe>
                </div>
                <div class="exercise_edit">
                  <%= link_to edit_exercise_path(exercise), class: "link" do %>
                    <i class="fa fa-edit edit_icon"></i>
                    <%= "編集" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <%# スケジュール管理 %>
    <% if user_signed_in? && current_user.id == @user.id %>
      <div class="show_wrapper other_show schedule_show">
        <div class="title_style">
          <h2 class="title"><i class="fas fa-angle-right space"></i>スケジュール管理</h2>
          <%= link_to new_schedule_path, class: "link" do %>
            <i class="fa fa-edit" aria-hidden="true"></i>
            <span class="pc_character">スケジュール追加</span>
            <span class="smart_character">追加</span>
          <% end %>
        </div>
        <table class="schedule_content">
          <tr>
            <th class="schedule_day">日付</th>
            <th class="schedule_day">部位</th>
            <th class="schedule_day">仕事</th>
            <th class="schedule_day">体調</th>
            <th class="schedule_day">編集</th>
          </tr>
          <% @schedules.each do |schedule| %>
            <tr>
              <td class="schedule_day"><%= schedule.training_date %></td>
              <td class="schedule_day"><%= schedule.part %></td>
              <td class="schedule_day"><%= schedule.work %></td>
              <td class="schedule_day"><%= schedule.shape %></td>
              <td class="schedule_day"><%= link_to "編集", edit_schedule_path(schedule), class: "link" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    <% end %>
  </div>
</div>