config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get 'users', to:'users/registrations#new'
  end
  resources :users, only: [:show]
  resources :diaries, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :schedules, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :exercises, only:[:new, :create, :show, :index, :edit, :update, :destroy]
  resources :counts, only: [:create, :update, :show]
  root 'exercises#index'
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @diaries = Diary.all.limit(4).order(id: "DESC")
    @q = Exercise.ransack(params[:q])
    @exercises = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @user = current_user
    @count = Count.find_by(user_id: @user)
    @schedules = Schedule.where(user_id: @user, training_date: Date.today)
    if @schedules.empty?
      @today_exercise = []
    elsif @schedules[0][:shape] == "不調"
      @today_exercise = Exercise.where(part: @schedules[0][:part],level: 1, user_id: current_user.id).order("RAND()").limit(1)
    else
      @today_exercise = Exercise.where(
                        part: @schedules[0][:part],level: 3, user_id: @user).
                        or(Exercise.where(
                        part: @schedules[0][:part],level: 2, user_id: @user )).
                      order("RAND()").limit(1)
    end
    @exercises = Exercise.where(user_id: @user)
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      flash[:notice] = '保存が完了しました'
      redirect_to exercise_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      flash[:notice] = '編集が完了しました'
      redirect_to exercise_path(current_user.id)
    else
      flash.now[:alert] = '入力を確認してください'
      render :edit
    end
  end

  def destroy
    exercise = Exercise.find(params[:id])
    exercise.destroy
    flash[:notice] = '１件のエクササイズを削除しました'
    redirect_to exercise_path(current_user.id)
  end

  private

  def exercise_params
    params.require(:exercise).permit(:url, :part, :level).merge(user_id: current_user.id)
  end

  def correct_user
    exercise = Exercise.find(params[:id])
    redirect_to root_url unless current_user.id == exercise.user_id
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_search.html.erb
<% if @exercises.empty? %>
  <p>まだ登録されたエクササイズはありません</p>
<% else %>
  <% @exercises.each do |exercise| %>
    <div class="content exercise_content">
      <div class="exercise_info">
        <span class="level">
          <% exercise.level.times do %>
            <i class="fas fa-dumbbell"></i>
          <% end %>
        </span>
        <%= exercise.part %>
      </div>
      <div class="iframe_wrap">
        <iframe width="400" height="225" src="https://www.youtube.com/embed/<%= exercise.url.last(11) %>"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
      </div>
      <div class="exercise_edit">
        <div class="exercise-edit-menu">
        </div>
        <div class="edit-menu">
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= paginate @exercises, remote: true %>

app/views/exercises/edit.html.erb
<%= form_with model: @exercise, local: true, method: :put do |f| %>
  <div class="user-content today-exercise-show new-exercise">
    <h1>このエクササイズを編集</h1>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="content exercise_content">
      <div class="exercise_info">
        <%= f.label :level, "Level", {class: "form-label"} %>
        <%= f.select :level, ["1","2", "3"], {}, {class: "form-control"} %>
        <%= f.label :part, "Part", {class: "form-label"} %>
        <%= f.select :part, ["二の腕", "お腹", "胸", "足"], {}, {class: "form-control"} %>
      </div>
      <div class="iframe_wrap">
        <iframe width="400" height="225" src="https://www.youtube.com/embed/<%= @exercise.url.last(11) %>"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
        <%= f.label :url, "YouTubeのURL", {class: "form-label"} %>
        <%= f.text_field :url, class: "form-control", placeholder: "YouTubeのURLを入力してください" %>
      </div>
      <div class="exercise-finish">
        <%= f.submit '更新する', class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
<% end %>

app/views/exercises/index.html.erb
<%= javascript_include_tag 'exercise/edit.js' %>
<div class="header-image">
  <div class="header-word">
    <h5>Continue training at home</h5>
    <h2>家でもジムと同等の継続体験を</h2>
  </div>
</div>

<div class="question-wrapper">
  <h1 class="question-title">いつもの家トレで<br>こんな想いをしたことありませんか？</h1>
  <ul class="image-wrapper">
    <li>
      <%= image_tag 'index/cheering.png', class: "question-image" %>
      <p>一緒に頑張る<br>仲間がいない<p>
    </li>
    <li>
      <%= image_tag 'index/yoga.png', class: "question-image" %>
      <p>同じトレーニングで<br>飽きる<p>
    </li>
    <li>
      <%= image_tag 'index/work.png', class: "question-image" %>
      <p>いつも仕事で<br>疲れてしまう<p>
    </li>
    <li>
      <%= image_tag 'index/schedule.png', class: "question-image" %>
      <p>毎日継続できない<p>
    </li>
    <li>
      <%= image_tag 'index/smartphone.png', class: "question-image" %>
      <p>トレーニングを<br>選ぶのも面倒<p>
    </li>
  </ul>
</div>
<div class="result-wrapper">
  <ul class="results">
    <h1>HomeGym Service</h1>
    <li class="result">
      <div class="result-numbers">
        <span class="result-number">1</span>
      </div>
      <div class="title-wrapper">
        <span class="result-title">トレーニング時間になったら通知が届く！(Comming soon...)</span>
      </div>
    </li>
    <li class="result">
      <div class="result-numbers">
        <span class="result-number">2</span>
      </div>
      <div class="title-wrapper">
        <span class="result-title">あなたのスケジュールに合わせた最適なエクササイズを自動で表示！</span>
      </div>
    </li>
    <li class="result">
      <div class="result-numbers">
        <span class="result-number">3</span>
      </div>
      <div class="title-wrapper">
        <span class="result-title">毎日新しいエクササイズに挑戦出来るから毎日が新鮮！</span>
      </div>
    </li>
    <li class="result">
      <div class="result-numbers">
        <span class="result-number">4</span>
      </div>
      <div class="title-wrapper">
        <span class="result-title">同じ目的を持った仲間と繋がってモチベーションアップ！</span>
      </div>
    </li>
    <li class="result">
      <div class="result-numbers">
        <span class="result-number">5</span>
      </div>
      <div class="title-wrapper">
        <span class="result-title">トレーニングを継続するほどあなたのペットが進化！毎日をより楽しく！</span>
      </div>
    </li>
  </ul>
</div>

<div class="banner">
  <%= image_tag 'バナー画像.png', class: "banner-image" %>
</div>

<%= search_form_for(@q, url: exercises_path, local: true, remote: true) do |f| %>
  <div class="search-exercise">
    <div class="user-content today-exercise-show new-exercise">
      <div class="content exercise_content">
        <h1>エクササイズを探してみる</h1>
        <div class="search-form">
          <div class="exercise_info">
            <%= f.label :level, "Level", {class: "form-label"} %>
            <%= f.select :level_eq, options_for_select([1, 2, 3]), {include_blank: true},
                {class: "form-control"} %>
            <%= f.label :part, "Part", {class: "form-label"} %>
            <%= f.select :part_eq, options_for_select(["二の腕", "お腹", "胸", "足"]), {include_blank: true},
                {class: "form-control"} %>
          </div>
          <div class="exercise-finish">
            <%= f.submit '検索', class: 'btn btn-warning btn-color' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="banner-index">
  <div class="user-content exercise-show">
    <div class="show_wrapper other_show">
      <div class="title_style">
        <h2 class="title"><i class="fas fa-angle-right space"></i>みんなのエクササイズ</h2>
        <%= link_to new_exercise_path, class: "link" do %>
          <i class="fa fa-edit" aria-hidden="true"></i>
          <span class="pc_character">エクササイズを追加</span>
          <span class="smart_character">追加</span>
        <% end %>
      </div>
      <div class="content_hidden">
        <div class="content_show content_show_ajax">
          <%= render partial:'exercises/search' %>
        </div>
      </div>
    </div>
  </div>

  <div class="user-content index-diary margin-top">
    <div class="show_wrapper">
      <div class="title_style">
        <h2 class="title"><i class="fas fa-angle-right space"></i>みんなの日記</h2>
          <%= link_to new_diary_path, class: "link" do %>
            <i class="fa fa-edit" aria-hidden="true"></i>
            <span class="pc_character">日記を投稿</span>
            <span class="smart_character">投稿</span>
          <% end %>
      </div>
      <div class="content_show">
        <% @diaries.each do |diary| %>
          <div class="content">
            <%= link_to user_path(diary.user.id), class: "link" do %>
              <div class="diary_user">
                <div class="user_icon">
                  <% if diary.user.image? %>
                    <%= image_tag diary.user.image_url(:thumb30), class: "user_icon_tag" %>
                  <% else %>
                    <%= image_tag 'user_image.png', :size =>'30x30', class: "user_icon_tag" %>
                  <% end %>
                </div>
                <div class="user_name">
                  <%= diary.user.name %>
                </div>
              </div>
            <% end %>
            <%= link_to diary_path(diary), class: "link" do %>
              <img src="<%= diary.image %>" class="diary_image" alt="日記画像">
              <li class="diary_content"><%= diary.content %></li>
            <% end %>
            <div class="diary_info">
              <div class="diary_like">
                <i class="fa fa-heart heart_red" aria-hidden="true"></i>
                <%= diary.likes.count %>
              </div>
              <div class="diary_day">
                <%= l diary.created_at %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to "他の日記もみる", diaries_path, class: "link other-diary btn btn-warning btn-color" %>
    </div>
  </div>
</div>

app/views/exercises/index.js.erb
$(".content_show_ajax").html("<%= j(render 'exercises/search') %>")

app/views/exercises/new.html.erb
<%= form_with model: @exercise, local: true, method: :post do |f| %>
  <div class="user-content today-exercise-show new-exercise">
    <h1>新しいエクササイズ</h1>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="content exercise_content">
      <div class="exercise_info">
        <%= f.label :level, "Level", {class: "form-label"} %>
        <%= f.select :level, ["1","2", "3"], {}, {class: "form-control"} %>
        <%= f.label :part, "Part", {class: "form-label"} %>
        <%= f.select :part, ["二の腕", "お腹", "胸", "足"], {}, {class: "form-control"} %>
      </div>
      <div class="iframe_wrap">
        <iframe width="400" height="225" src="https://www.youtube.com/embed/"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
        <%= f.label :url, "YouTubeのURL", {class: "form-label"} %>
        <%= f.text_field :url, class: "form-control", placeholder: "YouTubeのURLを入力してください" %>
      </div>
      <div class="exercise-finish">
        <%= f.submit 'このエクササイズを登録', class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
<% end %>

app/views/exercises/show.html.erb
<%= javascript_include_tag 'exercise/edit.js' %>
<div class="user-content today-exercise-show">
  <% if @today_exercise.empty? %>
    <div class="content exercise_content">
      <div class="exercise_info today-exercise-nothing">
        <%= "本日登録されたエクササイズはありません" %>
      </div>
      <div class="iframe_wrap">
        <iframe width="400" height="225" src="https://www.youtube.com/embed/"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
      </div>
      <div class="exercise-finish">
        <div class="exercise_edit">
        </div>
      </div>
    </div>
  <% else %>
    <h1>今日のトレーニングはこちら</h1>
    <div class="content exercise_content">
      <div class="exercise_info">
        <span class="level">
          <% @today_exercise[0][:level].times do %>
            <i class="fas fa-dumbbell"></i>
          <% end %>
        </span>
        <%= @today_exercise[0][:part] %>
      </div>
      <div class="iframe_wrap">
        <iframe width="400" height="225" src="https://www.youtube.com/embed/<%= @today_exercise[0][:url].last(11) %>"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
      </div>
      <div class="exercise-finish">
        <% if @count.nil? %>
          <%= link_to "トレーニング完了", counts_path, method: :post, class: "link btn btn-warning" %>
        <% else %>
          <%= link_to "トレーニング完了", count_path(@count), method: :patch, class: "link btn btn-warning" %>
        <% end %>

        <div class="exercise_edit">
          <%= link_to edit_exercise_path(@today_exercise[0][:id]), class: "link" do %>
            <i class="fa fa-edit edit_icon"></i>
            <%= "編集" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="user-content exercise-show">
  <div class="show_wrapper other_show">
    <div class="title_style">
      <h2 class="title"><i class="fas fa-angle-right space"></i>自分のエクササイズ一覧</h2>
      <%= link_to new_exercise_path, class: "link" do %>
        <i class="fa fa-edit" aria-hidden="true"></i>
        <span class="pc_character">エクササイズを追加</span>
        <span class="smart_character">追加</span>
      <% end %>
    </div>
    <div class="content_hidden">
      <div class="content_show">
        <% if @exercises.empty? %>
          <p>まだ登録されたエクササイズはありません</p>
        <% else %>
          <% @exercises.each do |exercise| %>
            <div class="content exercise_content">
              <div class="exercise_info">
                <span class="level">
                  <% exercise.level.times do %>
                    <i class="fas fa-dumbbell"></i>
                  <% end %>
                </span>
                <%= exercise.part %>
              </div>
              <div class="iframe_wrap">
                <iframe width="400" height="225" src="https://www.youtube.com/embed/<%= exercise.url.last(11) %>"
                        frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                        gyroscope; picture-in-picture" allowfullscreen>
                </iframe>
              </div>
              <div class="exercise_edit">
                <div class="exercise-edit-menu">
                  <i class="fas fa-ellipsis-h color"></i>
                </div>
                <div class="edit-menu">
                  <li><%= link_to "編集", edit_exercise_path(exercise), class: "link" %></li>
                  <li><%= link_to "削除", exercise_path(exercise), method: :delete, class: "link" %></li>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="exercise-finish">
        <% if @count.nil? %>
          <%= link_to "トレーニング完了", counts_path, method: :post, class: "link btn btn-warning" %>
        <% else %>
          <%= link_to "トレーニング完了", count_path(@count), method: :patch, class: "link btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</div>