config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get 'users', to:'users/registrations#new'
  end
  resources :users, only: [:show]
  resources :diaries, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :schedules, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :exercises, only:[:new, :create, :show, :index, :edit, :update, :destroy]
  resources :counts, only: [:create, :update, :show]
  root 'exercises#index'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <ul class="error_explanation">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300 rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="fade-layer"></div>
    <%= javascript_include_tag 'style/header.js' %>
    <% if notice.present? %>
      <p class="flash"><%= notice %></p>
    <% elsif alert.present? %>
      <p class="flash"><%= alert %></p>
    <% end %>
      <div class="header">
        <div><%= link_to "HomeGym", root_path, class: "header-logo" %></div>
        <ul class="lists">
          <% if user_signed_in? %>
            <li><%= link_to "今日トレ", exercise_path(current_user.id), class: "list" %></li>
            <li><%= link_to "みんなの日記", diaries_path, class: "list" %></li>
            <li><%= link_to "スケジュール", schedules_path, class: "list" %></li>
            <li><%= link_to "マイページ", user_path(current_user.id), class: "list" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list list-border" %></li>
          <% else %>
            <li><%= link_to "新規登録", new_user_registration_path, class: "list" %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: "list" %></li>
            <li><%= link_to "テストユーザーでログイン", users_guest_sign_in_path, method: :post, class: "list list-border" %></li>
          <% end %>
        </ul>
        <nav class="sp-nav">
          <ul>
            <% if user_signed_in? %>
              <li><%= link_to "今日トレ", exercise_path(current_user.id), class: "nav_list" %></li>
              <li><%= link_to "みんなの日記", diaries_path, class: "nav_list" %></li>
              <li><%= link_to "スケジュール", schedules_path, class: "nav_list" %></li>
              <li><%= link_to "マイページ", user_path(current_user.id), class: "nav_list" %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav_list" %></li>
            <% else %>
              <li><%= link_to "新規登録", new_user_registration_path, class: "nav_list" %></li>
              <li><%= link_to "ログイン", new_user_session_path, class: "nav_list" %></li>
              <li><%= link_to "テストユーザーでログイン", users_guest_sign_in_path, method: :post, class: "nav_list" %></li>
            <% end %>
              <li class="close"><span>閉じる</span></li>
          </ul>
        </nav>
        <div class="hamburger">
          <span></span>
        </div>
      </div>
      <div class="body">
        <%= yield %>
      </div>
      <div class="footer">
        <ul class="lists">
          <li><%= link_to "作者紹介", "https://www.wantedly.com/users/137861104", class: "list" %></li>
          <li><%= link_to "ご要望・お問い合わせ(Comming soon...)", "#", class: "list list-border" %></li>
        </ul>
        <p class="copyright">Copyright ©︎TETSURO ISHIBASHI All Rights Reserved.</p>
      </div>
  </body>
</html>